# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Check',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='审核名称')),
                ('status', models.CharField(choices=[('1', '等待'), ('2', '通过'), ('3', '拒绝')], default='等待', max_length=10, verbose_name='审核状态')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='计划名称')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openstack', models.CharField(max_length=255, verbose_name='问题描述')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='学生姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='任务名称')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('problem', models.ManyToManyField(related_name='Task', to='school.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='TaskOne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='任务名称')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('problem', models.ManyToManyField(related_name='TaskOne', to='school.Problem')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='教师姓名')),
                ('student', models.ManyToManyField(related_name='Teacher', to='school.Student')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='团队名称')),
                ('plan', models.ManyToManyField(related_name='Team', to='school.Plan')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='team',
            field=models.ManyToManyField(related_name='Teacher', to='school.Team'),
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ManyToManyField(related_name='Student', to='school.Team'),
        ),
        migrations.AddField(
            model_name='plan',
            name='task',
            field=models.ManyToManyField(related_name='Plan', to='school.Task'),
        ),
        migrations.AddField(
            model_name='plan',
            name='task1',
            field=models.ManyToManyField(related_name='Plan', to='school.TaskOne'),
        ),
        migrations.AddField(
            model_name='check',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student'),
        ),
        migrations.AddField(
            model_name='check',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Teacher'),
        ),
    ]
