# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-22 10:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='task',
            field=models.ManyToManyField(related_name='Plan', to='school.Task'),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='school.Team'),
        ),
        migrations.AlterField(
            model_name='task',
            name='problem',
            field=models.ManyToManyField(related_name='Task', to='school.Problem'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='team',
            field=models.ManyToManyField(related_name='Teacher', to='school.Team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='plan',
            field=models.ManyToManyField(related_name='Team', to='school.Plan'),
        ),
    ]
