# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 08:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='任务名称')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('problem', models.ManyToManyField(related_name='Task1', to='school.Problem')),
            ],
        ),
        migrations.RemoveField(
            model_name='taskone',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='taskone',
            name='problem',
        ),
        migrations.AlterField(
            model_name='plan',
            name='task1',
            field=models.ManyToManyField(related_name='Plan', to='school.Task1'),
        ),
        migrations.DeleteModel(
            name='TaskOne',
        ),
    ]
