# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180322_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('IDLE', '闲置'), ('WAIT', '等待'), ('ACCEPT', '通过'), ('REFUSE', '拒绝')], default='IDLE', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='student',
            field=models.ManyToManyField(related_name='Teacher', to='school.Student'),
        ),
    ]
