# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20180323_0811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='task1',
        ),
        migrations.AddField(
            model_name='task',
            name='task1',
            field=models.ManyToManyField(related_name='Task', to='school.Task1'),
        ),
    ]
