# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180323_0230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='team',
        ),
        migrations.AddField(
            model_name='student',
            name='team',
            field=models.ManyToManyField(related_name='Student', to='school.Team'),
        ),
    ]
