# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_auto_20180323_0837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=255, verbose_name='任务名称')),
                ('problem', models.ManyToManyField(related_name='Task2', to='school.Problem')),
            ],
        ),
        migrations.RemoveField(
            model_name='task',
            name='task1',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task1',
            name='object_id',
        ),
    ]
