# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-23 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20180323_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task1',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='task2',
            name='problem',
        ),
    ]
