# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-15 07:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('body_text', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('like_count', models.IntegerField(default=0, verbose_name='\u6587\u7ae0\u88ab\u70b9\u8d5e\u7684\u6b21\u6570')),
                ('status', models.CharField(choices=[('PUBLIC', '\u516c\u5f00\u6587\u7ae0'), ('HIDE', '\u9690\u85cf\u6587\u7ae0')], default='PUBLIC', max_length=10, verbose_name='\u6587\u7ae0\u72b6\u6001')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('users', models.ManyToManyField(related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, verbose_name='\u7f16\u8f91\u65f6\u95f4')),
                ('before_title', models.CharField(max_length=255, verbose_name='\u7f16\u8f91\u524d\u6807\u9898')),
                ('before_body_text', models.TextField(verbose_name='\u7f16\u8f91\u524d\u5185\u5bb9')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='\u7f16\u8f91\u6587\u7ae0')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d')),
                ('count', models.IntegerField(default=0, verbose_name='\u6807\u7b7e\u4f7f\u7528\u9891\u6b21')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags', verbose_name='\u5173\u8054tags\u8868'),
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7f16\u8f91\u4eba'),
        ),
    ]
