# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u7f16\u8f91\u4eba')),
                ('edit_time', models.DateTimeField(auto_now=True, verbose_name='\u6587\u7ae0\u7684\u7f16\u8f91\u65f6\u95f4')),
                ('before_title', models.CharField(max_length=255, verbose_name='\u7f16\u8f91\u524d\u6807\u9898')),
                ('before_body_text', models.TextField(verbose_name='\u7f16\u8f91\u524d\u5185\u5bb9')),
                ('Article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='\u5173\u8054\u6587\u7ae0\u8868')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagname', models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d')),
                ('count', models.IntegerField(verbose_name='\u6807\u7b7e\u4f7f\u7528\u9891\u6b21')),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags', verbose_name='\u5173\u8054tags\u8868'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='blog.Tags', verbose_name='\u5173\u8054Tags\u8868'),
        ),
    ]
