# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-03-21 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article', to='blog.Tags', verbose_name='关联tag表'),
        ),
    ]
