# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 11:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180312_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u6807\u7b7e\u540d'),
        ),
    ]
