# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20180308_1002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='user',
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ManyToManyField(related_name='article', to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
    ]
