# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-08 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_auto_20180308_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user',
            new_name='users',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='Article',
            new_name='article',
        ),
        migrations.RenameField(
            model_name='record',
            old_name='edit_time',
            new_name='update_datetime',
        ),
        migrations.RenameField(
            model_name='tags',
            old_name='tagname',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
