# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20180312_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='update_datetime',
            field=models.DateTimeField(auto_now=True, verbose_name='\u7f16\u8f91\u65f6\u95f4'),
        ),
    ]
