# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 07:49
from __future__ import unicode_literals

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180314_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='count',
            field=models.IntegerField(blank=True, verbose_name='\u6807\u7b7e\u4f7f\u7528\u9891\u6b21'),
        ),
    ]
