# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180314_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='count',
            field=models.IntegerField(default=0, verbose_name='\u6807\u7b7e\u4f7f\u7528\u9891\u6b21'),
        ),
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d'),
        ),
    ]
