# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180314_0749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='article', to='blog.Tags', verbose_name='\u6807\u7b7e'),
        ),
    ]
