# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-14 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20180314_0751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='name',
            field=models.CharField(max_length=50, verbose_name='\u6807\u7b7e\u540d'),
        ),
    ]
